### ISSUE TITLE
its not saving hasMany side of relationship

### ISSUE THREAD

**Issue by brunopedroso** [hoodiehq/ember-hoodie#25]
I tried to express it as a broken test but I could not find out a simple way to write a test that integrates the db... sorry. So I wrote an app that has a simple interface to create two related models: Conversation and Message. (a conversation hasMany messages; a message belongsTo a conversation).

https://github.com/brunopedroso/ember-hoodie-example-app

You can just install the app and navigate to index route, where you can signUp. Then create a conversation, click on it and then try posting a message to it. Then you'll run this action: https://github.com/brunopedroso/ember-hoodie-example-app/blob/master/app/controllers/conversation.js#L6

Interestingly, using the ui, the messages appear correctly when they are posted, showing the relationships is correctly setup in store memory. But when you reload the route (and it loads from db again) the list comes empty again.

I first made a test using a remote couchdb and could see that its saving the belongsTo side correctly (message.conversation), but its not saving the hasMany side (conversation.messages).

Its also possible to see the problem in indexedDB, through chrome inspector, clicking in the `by-sequence` table...

I did also put a debug message inside the adapter (https://github.com/hoodiehq/ember-hoodie/blob/master/addon/adapters/hoodie.js#L31) and could se that `props` object already comes without a `messages` ids array... 

Because of that I'm supposing we may have a problem in the serializer we're using...

**Comment by gr2m** [comment]
Hey @brunopedroso, thanks a lot for filing the issue and for creating the test app, this is super helpful! 

It’s most likely a problem with ember-hoodie, I think you might be the first to store relations with it. I hoped to have a bit of time to look into it today but unfortunately didn’t get to it :( 

I think another adapter we can look into to see how they did it is https://github.com/nolanlawson/ember-pouch, it seems to be much more battle tested, and we shoudl be able to adopt a lot of it as hoodie.store is basically only a wrapper around a PouchDB instance with a few extras.

If there is anything specifically about hoodie / hoodie.store, I’m happy to look into it

**Comment by arunprasadr-zz** [comment]
I Had to extend the JSONSerializer to serialize the hasMany side of the relationship.

```
//app/serializers/application.js

import DS from 'ember-data';

export default DS.JSONSerializer.extend({
  _shouldSerializeHasMany: function() {
    return true;
  }
});
```

**Comment by gr2m** [comment]
@arunprasadr is this something we should add to `ember-hoodie`? Or is it something that should be done on app level? @courajs

**Comment by brunopedroso** [comment]
I've researched a little and found out that this is just an Ember-Data decision - it doesn't serialize the 'many' side of the association.

(some refs [here](https://github.com/emberjs/data/issues/2068#issuecomment-48233710), [here](http://stackoverflow.com/questions/19093078/ember-data-saving-record-loses-has-many-relationships/24619032#24619032) and [here](https://www.toptal.com/emberjs/a-thorough-guide-to-ember-data#embeddedRecordsMixin) )

In this case, I guess @arunprasadr solution is actually an app's decision.

I only ended finding out also that _shouldSerializeHasMany now has a public version (which should be prefered, I suppose), and that the [this link](https://www.toptal.com/emberjs/a-thorough-guide-to-ember-data#embeddedRecordsMixin)) presents an alternative solution. (it's even [documented](https://guides.emberjs.com/v2.7.0/models/customizing-serializers/#toc_embeddedrecordmixin))

I updated the example app to serialize that relationsship and it's now working like a charm =)

Closing this issue.
Thanks for your attention.

**Comment by gr2m** [comment]
outstanding research, thanks @brunopedroso!

**Comment by gr2m** [comment]
actually, would you mind to add a note to the README of this repo for future reference with your findings? That’d be great

**Comment by brunopedroso** [comment]
@gr2m r u sure? Looks to me as such an specific and unrelated problem... specially because the project readme is still so synthetic... I guess the issue can already be a sufficient reference, dont U agree?

**Comment by gr2m** [comment]
you are right :) If it comes up more often, we can still add a note to the README. I’m just very new to all things Ember myself. Thanks!
