### ISSUE TITLE
Allow configuration in config/environment.js

### ISSUE THREAD

**Issue by courajs** [hoodiehq/ember-hoodie#4]
Allow configuring like:

``` js
hoodie: {
  server: {
  },
  client: {
  }
}
```

Link to the config sections for hoodie-server and hoodie-client

**Comment by gr2m** [comment]
Options for server are here:
https://github.com/hoodiehq/hoodie#usage

Options for client are here:
https://github.com/hoodiehq/hoodie-client#constructor

One thing we should do by default (if we can) is to default `hoodie.server.inMemory` to true for test environment

**Comment by gr2m** [comment]
Started implementing the server bits via https://github.com/hoodiehq/ember-hoodie/issues/15

**Comment by brunopedroso** [comment]
I guess this one is already implemented, right?

**Comment by gr2m** [comment]
jap, looks like it :)
