### ISSUE TITLE
upgrade hoodie dependencies

### ISSUE THREAD

**Issue by brunopedroso** [hoodiehq/ember-hoodie#55]
Version 2.2.3 is from oct/16. It references hoodie-client@ˆ6.0.0 (its at 10.0.2 already!)

Is there preventing us to upgrade?

**Comment by brunopedroso** [comment]
looks like master is already updated. Is it just a matter of releasing?

**Comment by gr2m** [comment]
yes looks like semantic-release failed on last build due to a timeout: https://travis-ci.org/hoodiehq/ember-hoodie/jobs/220821417#L2313

You can try to restart the build, maybe that will fix it. It would be even better to research if there is a setting for the timeout so we can increase it?

**Comment by brunopedroso** [comment]
I'd love to try restarting the build, but I guess I'm not allowed to...

**Comment by gr2m** [comment]
I’ve restarted the build and invited you to the Hoodie Contributors Team, so you should be able to do it yourself in future. Welcome :)

**Comment by gr2m** [comment]
unfortunately neither the [number of attempts](https://github.com/semantic-release/travis-deploy-once/blob/master/src.js#L40) nor the [timeout between attempts](https://github.com/semantic-release/travis-deploy-once/blob/master/src.js#L76) is configurable.

I’ll try to reduce the amount of test on travis if the current build finishes and fails again

**Comment by gr2m** [comment]
last build passed, ember-hoodie@2.3.0 was released
https://github.com/hoodiehq/ember-hoodie/releases/tag/v2.3.0

**Comment by brunopedroso** [comment]
> welcome

Thanks! Hope I can help =)

**Comment by brunopedroso** [comment]
Interestingly, the logs I see in the build still show the semantic-release error:

https://travis-ci.org/hoodiehq/ember-hoodie/jobs/220821417#L2313
(its the same link you posted earlier)

Can we see the logs of the new successful run?!
